### ISSUE TITLE
Does this generator also supports NoSQL Database like MongoDB.

### ISSUE THREAD

**Issue by DareUrDream** [elhoutico/jhipster-composite-key-server-blueprint#7]
Does this generator also supports NoSQL Database like MongoDB. Also do you have working sample of this blueprint.  The one uploaded in the test samples are having some issues when used with jHispter version 6.8.0

Thanks

**Comment by yelhouti** [comment]
@DareUrDream most NoSql databases don't have composite keys, so I don't think so...

**Comment by DareUrDream** [comment]
Sure Thanks
